global:
  database:
    host:
    port:
    username:
    ssl:
      mode:
      rootCert:
    createDatabase:
    originalDatabase:

  databaseSecret:
    name:
    key:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

  usageSender:
    apiUsageInternalServerAddr:

httpPort: 8080
grpcPort: 8081
internalGrpcPort: 8082

database:
  database: user_manager

defaultOrganization:
  title: Default Organization
  userIds:
  - admin@example.com
  tenantId: default-tenant-id

defaultProject:
  title: Default Project
  kubernetesNamespace: default
  userIds:
  - admin@example.com

kms:
  enable: false
  keyAlias:
  region:
  assumeRole:

replicaCount: 1
image:
  repository: public.ecr.aws/cloudnatix/llmariner/user-manager-server
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"

livenessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 3
  failureThreshold: 5
  timeoutSeconds: 3

podSecurityContext:
  fsGroup: 2000
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
